<a href="https://colab.research.google.com/github/deepjyoti27/Google-Microsoft-Preparation/blob/main/Day_3_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
labels=['a','b','c']
my_data=[10,20,30]
arr=np.array(my_data)
d={'a':10,'b':20,'c':30}
# my_data
# arr
# d
# pd.Series(data=my_data)
#
# pd.Series(data=my_data,index=labels)
# pd.Series(arr)
# pd.Series(d)
# pd.Series(data=[sum,print,len])
# pd.Series(data=labels)
ser1=pd.Series([1,2,3,4],index=['USA','Germany','USSR','Japan'])
ser2=pd.Series([1,2,5,4],index=['USA','Germany','Italy','Japan'])
# ser1['USA']
# ser1+ser2

ser1+ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [ ]:
import numpy as np
import pandas as pd

from numpy.random import randn
np.random.seed(101)
df=pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
#df
df['W']
#df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [ ]:
type(df)
df['X']

A    0.628133
B   -0.319318
C    0.740122
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [ ]:
df[['W','Z']]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [ ]:
df['new']=df['W']+df['Y']
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [ ]:
#df.drop('new',axis=1,inplace=True)
#df.loc['A']
df.iloc[2]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [ ]:
df.loc['B','Y']

np.float64(-0.8480769834036315)

In [ ]:
df.loc[['A','B'],['W','Y']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [ ]:
print("heello world!")

heello world!

In [ ]:
df=pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652